server:
  port: 8086
spring:
  goods:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.112.31?useUnicode=true&characterEncoding=utf-8
      username: r_58swap
      password: oxit745vkeWcAAy9
  photocode:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.112.36?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 58test
logging:
  config: classpath:logback.xml