server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.112.31?useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://192.168.112.31/58test?useUnicode=true&characterEncoding=utf-8
#    username: r_58swap
#    password: oxit745vkeWcAAy9



    url: jdbc:mysql://192.168.112.36?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 58test